vich_uploader:
    db_driver: orm
    mappings:
        player_images:
            uri_prefix: /img/player
            upload_destination: '%kernel.project_dir%/public/img/player'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
